name: macOS Runner Delayed Hello World

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: macos-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"

      - name: Delay
        run: sleep 120 # Delay for 2 minutes (120 seconds)
